import localFont from "next/font/local";
import "./globals.css";
import Footer from "./_components/footer/Footer";
import SubscribeSection from "./_components/subscribeSection/SubscribeSection";
import Header from "./_components/header/Header";
import Navigation from "./_components/navigation/Navigation";
import Content from "./_components/content/content";
import DeliveryStatus from "./_components/deliveryStatus/deliveryStatus";
import ProductPage from "./_components/ProductPage.jsx/ProductPage";
import MightInteresYou from "./_components/mightInterestyou/MightInteresYou";
import SimilarArticles from "./_components/similarArticles/SimilarArticles";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Navigation />
        <Content />
        <ProductPage />
        <SimilarArticles />
        <MightInteresYou />
        <DeliveryStatus />
        <main>{children}</main>

        <SubscribeSection />
        <Footer />
      </body>
    </html>
  );
}
